# Generated by Django 5.0.7 on 2024-07-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_institution_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'institution', 'verbose_name_plural': 'institutions'},
        ),
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
